let initialData = [
    {
        activities: [
            {
                id: 437758,
                parentId: 0,
                orderChild: 0,
                name: 'Capability 1',
                color: '#004c84',
                summary: null,
                heatmaps: [],
                activities: [
                    {
                        id: 437760,
                        parentId: 437758,
                        orderChild: 1,
                        name: 'Capability 1 - Child 2',
                        color: '',
                        summary: null,
                        heatmaps: [],
                        activities: [
                            {
                                id: 437765,
                                parentId: 437760,
                                orderChild: 1,
                                name: 'Capability 1 - Child 2 - Child 3 ',
                                color: '',
                                summary: null,
                                heatmaps: [],
                                activities: [],
                                isParent: false,
                                inputs: [],
                                outputs: [],
                                systems: [],
                                stakeholders: [],
                                customers: [],
                                suppliers: [],
                                levelNumber: '1.1',
                                organizationalGoals: [],
                                opportunities: [],
                                process: [],
                                processCapabilityIds: [],
                                node: 2,
                            },
                            {
                                id: 437766,
                                parentId: 437760,
                                orderChild: 2,
                                name: 'Capability 1 - Child 2 - Child 2',
                                color: '',
                                summary: null,
                                heatmaps: [],
                                activities: [],
                                isParent: false,
                                inputs: [],
                                outputs: [],
                                systems: [],
                                stakeholders: [],
                                customers: [],
                                suppliers: [],
                                levelNumber: '1.2',
                                organizationalGoals: [],
                                opportunities: [],
                                process: [],
                                processCapabilityIds: [],
                                node: 2,
                            },
                            {
                                id: 437767,
                                parentId: 437760,
                                orderChild: 3,
                                name: 'Capability 1 - Child 2 - Child 1',
                                color: '',
                                summary: null,
                                heatmaps: [],
                                activities: [],
                                isParent: false,
                                inputs: [],
                                outputs: [],
                                systems: [],
                                stakeholders: [],
                                customers: [],
                                suppliers: [],
                                levelNumber: '1.3',
                                organizationalGoals: [],
                                opportunities: [],
                                process: [],
                                processCapabilityIds: [],
                                node: 2,
                            },
                            {
                                id: 445455,
                                parentId: 437760,
                                orderChild: 4,
                                name: 'Capability 1 - Child 2 - Child 4',
                                color: '',
                                summary: null,
                                heatmaps: [],
                                activities: [],
                                isParent: false,
                                inputs: [],
                                outputs: [],
                                systems: [],
                                stakeholders: [],
                                customers: [],
                                suppliers: [],
                                levelNumber: '1.4',
                                organizationalGoals: [],
                                opportunities: [],
                                process: [],
                                processCapabilityIds: [],
                                node: 2,
                            },
                        ],
                        isParent: false,
                        inputs: [],
                        outputs: [],
                        systems: [],
                        stakeholders: [],
                        customers: [],
                        suppliers: [],
                        levelNumber: '1',
                        organizationalGoals: [],
                        opportunities: [],
                        process: [],
                        processCapabilityIds: [],
                        node: 1,
                    },
                    {
                        id: 437761,
                        parentId: 437758,
                        orderChild: 2,
                        name: 'Capability 1 - Child 1',
                        color: '',
                        summary: null,
                        heatmaps: [],
                        activities: [
                            {
                                id: 123123123,
                                parentId: 437761,
                                orderChild: 0,
                                name: 'Capability 1 - Child 1 - Child 1',
                                color: '',
                                summary: null,
                                heatmaps: [],
                                activities: [],
                                isParent: false,
                                inputs: [],
                                outputs: [],
                                systems: [],
                                stakeholders: [],
                                customers: [],
                                suppliers: [],
                                levelNumber: '2',
                                organizationalGoals: [],
                                opportunities: [],
                                process: [],
                                processCapabilityIds: [],
                                node: 2,
                            },
                        ],
                        isParent: false,
                        inputs: [],
                        outputs: [],
                        systems: [],
                        stakeholders: [],
                        customers: [],
                        suppliers: [],
                        levelNumber: '2',
                        organizationalGoals: [],
                        opportunities: [],
                        process: [],
                        processCapabilityIds: [],
                        node: 1,
                    },
                ],
                isParent: false,
                inputs: [],
                outputs: [],
                systems: [],
                stakeholders: [],
                customers: [],
                suppliers: [],
                levelNumber: null,
                organizationalGoals: [],
                opportunities: [],
                process: [],
                processCapabilityIds: [],
                node: 0,
            },
            {
                id: 437759,
                parentId: 0,
                orderChild: 0,
                name: 'Capability 2',
                color: '#009a81',
                summary: null,
                heatmaps: [],
                activities: [
                    {
                        id: 437787,
                        parentId: 437759,
                        orderChild: 1,
                        name: 'Capability 2 - Child 2',
                        color: '',
                        summary: null,
                        heatmaps: [],
                        activities: [],
                        isParent: false,
                        inputs: [],
                        outputs: [],
                        systems: [],
                        stakeholders: [],
                        customers: [],
                        suppliers: [],
                        levelNumber: '6',
                        organizationalGoals: [],
                        opportunities: [],
                        process: [],
                        processCapabilityIds: [],
                        node: 1,
                    },
                    {
                        id: 437789,
                        parentId: 437759,
                        orderChild: 3,
                        name: 'Capability 2 - Child 1',
                        color: '',
                        summary: null,
                        heatmaps: [],
                        activities: [
                            {
                                id: 437805,
                                parentId: 437789,
                                orderChild: 4,
                                name: 'Capability 2 - Child 1 - Child 1',
                                color: '',
                                summary: null,
                                heatmaps: [],
                                activities: [],
                                isParent: false,
                                inputs: [],
                                outputs: [],
                                systems: [],
                                stakeholders: [],
                                customers: [],
                                suppliers: [],
                                levelNumber: '8.4',
                                organizationalGoals: [],
                                opportunities: [],
                                process: [],
                                processCapabilityIds: [],
                                node: 2,
                            },
                        ],
                        isParent: false,
                        inputs: [],
                        outputs: [],
                        systems: [],
                        stakeholders: [],
                        customers: [],
                        suppliers: [],
                        levelNumber: '8',
                        organizationalGoals: [],
                        opportunities: [],
                        process: [],
                        processCapabilityIds: [],
                        node: 1,
                    },
                ],
                isParent: false,
                inputs: [],
                outputs: [],
                systems: [],
                stakeholders: [],
                customers: [],
                suppliers: [],
                levelNumber: null,
                organizationalGoals: [],
                opportunities: [],
                process: [],
                processCapabilityIds: [],
                node: 0,
            },
        ],
    },
]

let filterActivities = function (data) {
    return data.map((activity) => {
        let filteredActivity = {
            id: activity.id,
            name: activity.name,
            parentId: activity.parentId,
            node: activity.node,
            activities: activity.activities && activity.activities.length > 0 ? filterActivities(activity.activities) : [],
        }

        return filteredActivity
    })
}

let sortActivities = function (data, criteria) {
    // sort the current level by criteria
    data.sort((a, b) => {
        if (a[criteria] < b[criteria]) {
            return -1
        }
        if (a[criteria] > b[criteria]) {
            return 1
        }
        return 0
    })

    // sort each nested level (if activities array exists and is not empty)
    data.forEach((activity) => {
        if (activity.activities && activity.activities.length > 0) {
            sortActivities(activity.activities, criteria)
        }
    })

    return data
}

let flattenActivities = function (data) {
    let result = []

    for (let activity of data) {
        // Push current activity to result array
        result.push({
            id: activity.id,
            name: activity.name,
            parentId: activity.parentId,
            node: activity.node,
            activities: [], // flatten, so no nested activities
        })

        // If there are nested activities, flatten and push them too
        if (activity.activities && activity.activities.length > 0) {
            result = result.concat(flattenActivities(activity.activities))
        }
    }

    return result
}

// Initialize the DataTable with 'dataWithNodes'
$(function () {
    // Call the function with your data
    let filteredData = filterActivities(initialData[0].activities)

    let sortedData = sortActivities(filteredData, 'name')

    let flattenedData = flattenActivities(sortedData)

    $('#myTable').DataTable({
        data: flattenedData,
        columns: [
            {
                title: 'Name',
                data: 'name',
                render: function (data, type, row) {
                    if (type === 'display') {
                        let color = colors[row.node % colors.length]
                        return '<span style="padding-left:' + row.node * 30 + 'px;">' + data + '</span>'
                    }
                    return data
                },
            },
            {
                title: 'Id',
                data: 'id',
            },
            {
                title: 'Parent Id',
                data: 'parentId',
            },
            {
                title: 'Node',
                data: 'node',
            },
        ],
    })
})


{
    "activities": [
        {
            "id": 437758,
            "parentId": 0,
            "orderChild": 0,
            "name": "New Primary Capability",
            "color": "#004c84",
            "summary": null,
            "heatmaps": [],
            "activities": [
                {
                    "id": 437760,
                    "parentId": 437758,
                    "orderChild": 1,
                    "name": "New Offer",
                    "color": "",
                    "summary": null,
                    "heatmaps": [],
                    "activities": [
                        {
                            "id": 437765,
                            "parentId": 437760,
                            "orderChild": 1,
                            "name": "Accept new Offer",
                            "color": "",
                            "summary": null,
                            "heatmaps": [],
                            "activities": [],
                            "isParent": false,
                            "inputs": [],
                            "outputs": [],
                            "systems": [],
                            "stakeholders": [],
                            "customers": [],
                            "suppliers": [],
                            "levelNumber": "1.1",
                            "organizationalGoals": [],
                            "opportunities": [],
                            "process": [],
                            "processCapabilityIds": []
                        },
                        {
                            "id": 437766,
                            "parentId": 437760,
                            "orderChild": 2,
                            "name": "Raw Materials",
                            "color": "",
                            "summary": null,
                            "heatmaps": [],
                            "activities": [],
                            "isParent": false,
                            "inputs": [],
                            "outputs": [],
                            "systems": [],
                            "stakeholders": [],
                            "customers": [],
                            "suppliers": [],
                            "levelNumber": "1.2",
                            "organizationalGoals": [],
                            "opportunities": [],
                            "process": [],
                            "processCapabilityIds": []
                        },
                        {
                            "id": 437767,
                            "parentId": 437760,
                            "orderChild": 3,
                            "name": "Supply Schedules",
                            "color": "",
                            "summary": null,
                            "heatmaps": [],
                            "activities": [],
                            "isParent": false,
                            "inputs": [],
                            "outputs": [],
                            "systems": [],
                            "stakeholders": [],
                            "customers": [],
                            "suppliers": [],
                            "levelNumber": "1.3",
                            "organizationalGoals": [],
                            "opportunities": [],
                            "process": [],
                            "processCapabilityIds": []
                        },
                        {
                            "id": 445455,
                            "parentId": 437760,
                            "orderChild": 4,
                            "name": "New Capability",
                            "color": "",
                            "summary": null,
                            "heatmaps": [],
                            "activities": [],
                            "isParent": false,
                            "inputs": [],
                            "outputs": [],
                            "systems": [],
                            "stakeholders": [],
                            "customers": [],
                            "suppliers": [],
                            "levelNumber": "1.4",
                            "organizationalGoals": [],
                            "opportunities": [],
                            "process": [],
                            "processCapabilityIds": []
                        }
                    ],
                    "isParent": false,
                    "inputs": [],
                    "outputs": [],
                    "systems": [],
                    "stakeholders": [],
                    "customers": [],
                    "suppliers": [],
                    "levelNumber": "1",
                    "organizationalGoals": [],
                    "opportunities": [],
                    "process": [],
                    "processCapabilityIds": []
                },
                {
                    "id": 437761,
                    "parentId": 437758,
                    "orderChild": 2,
                    "name": "Operations",
                    "color": "",
                    "summary": null,
                    "heatmaps": [],
                    "activities": [
                        {
                            "id": 437768,
                            "parentId": 437761,
                            "orderChild": 1,
                            "name": "Manufacturing",
                            "color": "",
                            "summary": null,
                            "heatmaps": [],
                            "activities": [],
                            "isParent": false,
                            "inputs": [],
                            "outputs": [],
                            "systems": [],
                            "stakeholders": [],
                            "customers": [],
                            "suppliers": [],
                            "levelNumber": "2.1",
                            "organizationalGoals": [],
                            "opportunities": [],
                            "process": [],
                            "processCapabilityIds": []
                        },
                        {
                            "id": 437769,
                            "parentId": 437761,
                            "orderChild": 2,
                            "name": "Packaging",
                            "color": "",
                            "summary": null,
                            "heatmaps": [],
                            "activities": [],
                            "isParent": false,
                            "inputs": [],
                            "outputs": [],
                            "systems": [],
                            "stakeholders": [],
                            "customers": [],
                            "suppliers": [],
                            "levelNumber": "2.2",
                            "organizationalGoals": [],
                            "opportunities": [],
                            "process": [],
                            "processCapabilityIds": []
                        },
                        {
                            "id": 437770,
                            "parentId": 437761,
                            "orderChild": 3,
                            "name": "Production Control",
                            "color": "",
                            "summary": null,
                            "heatmaps": [],
                            "activities": [],
                            "isParent": false,
                            "inputs": [],
                            "outputs": [],
                            "systems": [],
                            "stakeholders": [],
                            "customers": [],
                            "suppliers": [],
                            "levelNumber": "2.3",
                            "organizationalGoals": [],
                            "opportunities": [],
                            "process": [],
                            "processCapabilityIds": []
                        },
                        {
                            "id": 437771,
                            "parentId": 437761,
                            "orderChild": 4,
                            "name": "Quality Control",
                            "color": "",
                            "summary": null,
                            "heatmaps": [],
                            "activities": [],
                            "isParent": false,
                            "inputs": [],
                            "outputs": [],
                            "systems": [],
                            "stakeholders": [],
                            "customers": [],
                            "suppliers": [],
                            "levelNumber": "2.4",
                            "organizationalGoals": [],
                            "opportunities": [],
                            "process": [],
                            "processCapabilityIds": []
                        },
                        {
                            "id": 437772,
                            "parentId": 437761,
                            "orderChild": 5,
                            "name": "Maintenance",
                            "color": "",
                            "summary": null,
                            "heatmaps": [],
                            "activities": [],
                            "isParent": false,
                            "inputs": [],
                            "outputs": [],
                            "systems": [],
                            "stakeholders": [],
                            "customers": [],
                            "suppliers": [],
                            "levelNumber": "2.5",
                            "organizationalGoals": [],
                            "opportunities": [],
                            "process": [],
                            "processCapabilityIds": []
                        }
                    ],
                    "isParent": false,
                    "inputs": [],
                    "outputs": [],
                    "systems": [],
                    "stakeholders": [],
                    "customers": [],
                    "suppliers": [],
                    "levelNumber": "2",
                    "organizationalGoals": [],
                    "opportunities": [],
                    "process": [],
                    "processCapabilityIds": []
                },
                {
                    "id": 437762,
                    "parentId": 437758,
                    "orderChild": 3,
                    "name": "Outbound Logistics",
                    "color": "",
                    "summary": null,
                    "heatmaps": [],
                    "activities": [
                        {
                            "id": 437773,
                            "parentId": 437762,
                            "orderChild": 1,
                            "name": "Finishing Goods",
                            "color": "",
                            "summary": null,
                            "heatmaps": [],
                            "activities": [],
                            "isParent": false,
                            "inputs": [],
                            "outputs": [],
                            "systems": [],
                            "stakeholders": [],
                            "customers": [],
                            "suppliers": [],
                            "levelNumber": "3.1",
                            "organizationalGoals": [],
                            "opportunities": [],
                            "process": [],
                            "processCapabilityIds": []
                        },
                        {
                            "id": 437774,
                            "parentId": 437762,
                            "orderChild": 2,
                            "name": "Order Handling",
                            "color": "",
                            "summary": null,
                            "heatmaps": [],
                            "activities": [],
                            "isParent": false,
                            "inputs": [],
                            "outputs": [],
                            "systems": [],
                            "stakeholders": [],
                            "customers": [],
                            "suppliers": [],
                            "levelNumber": "3.2",
                            "organizationalGoals": [],
                            "opportunities": [],
                            "process": [],
                            "processCapabilityIds": []
                        },
                        {
                            "id": 437775,
                            "parentId": 437762,
                            "orderChild": 3,
                            "name": "Dispatch",
                            "color": "",
                            "summary": null,
                            "heatmaps": [],
                            "activities": [],
                            "isParent": false,
                            "inputs": [],
                            "outputs": [],
                            "systems": [],
                            "stakeholders": [],
                            "customers": [],
                            "suppliers": [],
                            "levelNumber": "3.3",
                            "organizationalGoals": [],
                            "opportunities": [],
                            "process": [],
                            "processCapabilityIds": []
                        },
                        {
                            "id": 437776,
                            "parentId": 437762,
                            "orderChild": 4,
                            "name": "Delivery",
                            "color": "",
                            "summary": null,
                            "heatmaps": [],
                            "activities": [],
                            "isParent": false,
                            "inputs": [],
                            "outputs": [],
                            "systems": [],
                            "stakeholders": [],
                            "customers": [],
                            "suppliers": [],
                            "levelNumber": "3.4",
                            "organizationalGoals": [],
                            "opportunities": [],
                            "process": [],
                            "processCapabilityIds": []
                        },
                        {
                            "id": 437777,
                            "parentId": 437762,
                            "orderChild": 5,
                            "name": "Invoicing",
                            "color": "",
                            "summary": null,
                            "heatmaps": [],
                            "activities": [],
                            "isParent": false,
                            "inputs": [],
                            "outputs": [],
                            "systems": [],
                            "stakeholders": [],
                            "customers": [],
                            "suppliers": [],
                            "levelNumber": "3.5",
                            "organizationalGoals": [],
                            "opportunities": [],
                            "process": [],
                            "processCapabilityIds": []
                        }
                    ],
                    "isParent": false,
                    "inputs": [],
                    "outputs": [],
                    "systems": [],
                    "stakeholders": [],
                    "customers": [],
                    "suppliers": [],
                    "levelNumber": "3",
                    "organizationalGoals": [],
                    "opportunities": [],
                    "process": [],
                    "processCapabilityIds": []
                },
                {
                    "id": 437763,
                    "parentId": 437758,
                    "orderChild": 4,
                    "name": "Sales & Marketing",
                    "color": "",
                    "summary": null,
                    "heatmaps": [],
                    "activities": [
                        {
                            "id": 437778,
                            "parentId": 437763,
                            "orderChild": 1,
                            "name": "Customer Management",
                            "color": "",
                            "summary": null,
                            "heatmaps": [],
                            "activities": [],
                            "isParent": false,
                            "inputs": [],
                            "outputs": [],
                            "systems": [],
                            "stakeholders": [],
                            "customers": [],
                            "suppliers": [],
                            "levelNumber": "4.1",
                            "organizationalGoals": [],
                            "opportunities": [],
                            "process": [],
                            "processCapabilityIds": []
                        },
                        {
                            "id": 437779,
                            "parentId": 437763,
                            "orderChild": 2,
                            "name": "Order Taking",
                            "color": "",
                            "summary": null,
                            "heatmaps": [],
                            "activities": [],
                            "isParent": false,
                            "inputs": [],
                            "outputs": [],
                            "systems": [],
                            "stakeholders": [],
                            "customers": [],
                            "suppliers": [],
                            "levelNumber": "4.2",
                            "organizationalGoals": [],
                            "opportunities": [],
                            "process": [],
                            "processCapabilityIds": []
                        },
                        {
                            "id": 437780,
                            "parentId": 437763,
                            "orderChild": 3,
                            "name": "Promotion",
                            "color": "",
                            "summary": null,
                            "heatmaps": [],
                            "activities": [],
                            "isParent": false,
                            "inputs": [],
                            "outputs": [],
                            "systems": [],
                            "stakeholders": [],
                            "customers": [],
                            "suppliers": [],
                            "levelNumber": "4.3",
                            "organizationalGoals": [],
                            "opportunities": [],
                            "process": [],
                            "processCapabilityIds": []
                        },
                        {
                            "id": 437781,
                            "parentId": 437763,
                            "orderChild": 4,
                            "name": "Sales Analysis",
                            "color": "",
                            "summary": null,
                            "heatmaps": [],
                            "activities": [],
                            "isParent": false,
                            "inputs": [],
                            "outputs": [],
                            "systems": [],
                            "stakeholders": [],
                            "customers": [],
                            "suppliers": [],
                            "levelNumber": "4.4",
                            "organizationalGoals": [],
                            "opportunities": [],
                            "process": [],
                            "processCapabilityIds": []
                        },
                        {
                            "id": 437782,
                            "parentId": 437763,
                            "orderChild": 5,
                            "name": "Market Research",
                            "color": "",
                            "summary": null,
                            "heatmaps": [],
                            "activities": [],
                            "isParent": false,
                            "inputs": [],
                            "outputs": [],
                            "systems": [],
                            "stakeholders": [],
                            "customers": [],
                            "suppliers": [],
                            "levelNumber": "4.5",
                            "organizationalGoals": [],
                            "opportunities": [],
                            "process": [],
                            "processCapabilityIds": []
                        }
                    ],
                    "isParent": false,
                    "inputs": [],
                    "outputs": [],
                    "systems": [],
                    "stakeholders": [],
                    "customers": [],
                    "suppliers": [],
                    "levelNumber": "4",
                    "organizationalGoals": [],
                    "opportunities": [],
                    "process": [],
                    "processCapabilityIds": []
                },
                {
                    "id": 437764,
                    "parentId": 437758,
                    "orderChild": 5,
                    "name": "Services",
                    "color": "",
                    "summary": null,
                    "heatmaps": [],
                    "activities": [
                        {
                            "id": 437783,
                            "parentId": 437764,
                            "orderChild": 1,
                            "name": "Warranties",
                            "color": "",
                            "summary": null,
                            "heatmaps": [],
                            "activities": [],
                            "isParent": false,
                            "inputs": [],
                            "outputs": [],
                            "systems": [],
                            "stakeholders": [],
                            "customers": [],
                            "suppliers": [],
                            "levelNumber": "5.1",
                            "organizationalGoals": [],
                            "opportunities": [],
                            "process": [],
                            "processCapabilityIds": []
                        },
                        {
                            "id": 437784,
                            "parentId": 437764,
                            "orderChild": 2,
                            "name": "Maintenance",
                            "color": "",
                            "summary": null,
                            "heatmaps": [],
                            "activities": [],
                            "isParent": false,
                            "inputs": [],
                            "outputs": [],
                            "systems": [],
                            "stakeholders": [],
                            "customers": [],
                            "suppliers": [],
                            "levelNumber": "5.2",
                            "organizationalGoals": [],
                            "opportunities": [],
                            "process": [],
                            "processCapabilityIds": []
                        },
                        {
                            "id": 437785,
                            "parentId": 437764,
                            "orderChild": 3,
                            "name": "Education & Training",
                            "color": "",
                            "summary": null,
                            "heatmaps": [],
                            "activities": [],
                            "isParent": false,
                            "inputs": [],
                            "outputs": [],
                            "systems": [],
                            "stakeholders": [],
                            "customers": [],
                            "suppliers": [],
                            "levelNumber": "5.3",
                            "organizationalGoals": [],
                            "opportunities": [],
                            "process": [],
                            "processCapabilityIds": []
                        },
                        {
                            "id": 437786,
                            "parentId": 437764,
                            "orderChild": 4,
                            "name": "Upgrades",
                            "color": "",
                            "summary": null,
                            "heatmaps": [],
                            "activities": [],
                            "isParent": false,
                            "inputs": [],
                            "outputs": [],
                            "systems": [],
                            "stakeholders": [],
                            "customers": [],
                            "suppliers": [],
                            "levelNumber": "5.4",
                            "organizationalGoals": [],
                            "opportunities": [],
                            "process": [],
                            "processCapabilityIds": []
                        }
                    ],
                    "isParent": false,
                    "inputs": [],
                    "outputs": [],
                    "systems": [],
                    "stakeholders": [],
                    "customers": [],
                    "suppliers": [],
                    "levelNumber": "5",
                    "organizationalGoals": [],
                    "opportunities": [],
                    "process": [],
                    "processCapabilityIds": []
                }
            ],
            "isParent": false,
            "inputs": [],
            "outputs": [],
            "systems": [],
            "stakeholders": [],
            "customers": [],
            "suppliers": [],
            "levelNumber": null,
            "organizationalGoals": [],
            "opportunities": [],
            "process": [],
            "processCapabilityIds": []
        },
        {
            "id": 437759,
            "parentId": 0,
            "orderChild": 0,
            "name": "Supporting/Enabling",
            "color": "#009a81",
            "summary": null,
            "heatmaps": [],
            "activities": [
                {
                    "id": 437787,
                    "parentId": 437759,
                    "orderChild": 1,
                    "name": "Firm Infrastructure",
                    "color": "",
                    "summary": null,
                    "heatmaps": [],
                    "activities": [
                        {
                            "id": 437791,
                            "parentId": 437787,
                            "orderChild": 1,
                            "name": "Legal",
                            "color": "",
                            "summary": null,
                            "heatmaps": [],
                            "activities": [
                                {
                                    "id": 437794,
                                    "parentId": 437791,
                                    "orderChild": 1,
                                    "name": "Legal L3 A",
                                    "color": "",
                                    "summary": null,
                                    "heatmaps": [],
                                    "activities": [],
                                    "isParent": false,
                                    "inputs": [],
                                    "outputs": [],
                                    "systems": [],
                                    "stakeholders": [],
                                    "customers": [],
                                    "suppliers": [],
                                    "levelNumber": "6.1.1",
                                    "organizationalGoals": [],
                                    "opportunities": [],
                                    "process": [],
                                    "processCapabilityIds": []
                                },
                                {
                                    "id": 437795,
                                    "parentId": 437791,
                                    "orderChild": 2,
                                    "name": "Legal L3 B",
                                    "color": "",
                                    "summary": null,
                                    "heatmaps": [],
                                    "activities": [],
                                    "isParent": false,
                                    "inputs": [],
                                    "outputs": [],
                                    "systems": [],
                                    "stakeholders": [],
                                    "customers": [],
                                    "suppliers": [],
                                    "levelNumber": "6.1.2",
                                    "organizationalGoals": [],
                                    "opportunities": [],
                                    "process": [],
                                    "processCapabilityIds": []
                                }
                            ],
                            "isParent": false,
                            "inputs": [],
                            "outputs": [],
                            "systems": [],
                            "stakeholders": [],
                            "customers": [],
                            "suppliers": [],
                            "levelNumber": "6.1",
                            "organizationalGoals": [],
                            "opportunities": [],
                            "process": [],
                            "processCapabilityIds": []
                        },
                        {
                            "id": 437792,
                            "parentId": 437787,
                            "orderChild": 2,
                            "name": "Accounting",
                            "color": "",
                            "summary": null,
                            "heatmaps": [],
                            "activities": [
                                {
                                    "id": 437796,
                                    "parentId": 437792,
                                    "orderChild": 1,
                                    "name": "Accounting L3 A",
                                    "color": "",
                                    "summary": null,
                                    "heatmaps": [],
                                    "activities": [],
                                    "isParent": false,
                                    "inputs": [],
                                    "outputs": [],
                                    "systems": [],
                                    "stakeholders": [],
                                    "customers": [],
                                    "suppliers": [],
                                    "levelNumber": "6.2.1",
                                    "organizationalGoals": [],
                                    "opportunities": [],
                                    "process": [],
                                    "processCapabilityIds": []
                                }
                            ],
                            "isParent": false,
                            "inputs": [],
                            "outputs": [],
                            "systems": [],
                            "stakeholders": [],
                            "customers": [],
                            "suppliers": [],
                            "levelNumber": "6.2",
                            "organizationalGoals": [],
                            "opportunities": [],
                            "process": [],
                            "processCapabilityIds": []
                        },
                        {
                            "id": 437793,
                            "parentId": 437787,
                            "orderChild": 3,
                            "name": "Financial Management",
                            "color": "",
                            "summary": null,
                            "heatmaps": [],
                            "activities": [
                                {
                                    "id": 437797,
                                    "parentId": 437793,
                                    "orderChild": 1,
                                    "name": "Finance L3 A",
                                    "color": "",
                                    "summary": null,
                                    "heatmaps": [],
                                    "activities": [],
                                    "isParent": false,
                                    "inputs": [],
                                    "outputs": [],
                                    "systems": [],
                                    "stakeholders": [],
                                    "customers": [],
                                    "suppliers": [],
                                    "levelNumber": "6.3.1",
                                    "organizationalGoals": [],
                                    "opportunities": [],
                                    "process": [],
                                    "processCapabilityIds": []
                                }
                            ],
                            "isParent": false,
                            "inputs": [],
                            "outputs": [],
                            "systems": [],
                            "stakeholders": [],
                            "customers": [],
                            "suppliers": [],
                            "levelNumber": "6.3",
                            "organizationalGoals": [],
                            "opportunities": [],
                            "process": [],
                            "processCapabilityIds": []
                        }
                    ],
                    "isParent": false,
                    "inputs": [],
                    "outputs": [],
                    "systems": [],
                    "stakeholders": [],
                    "customers": [],
                    "suppliers": [],
                    "levelNumber": "6",
                    "organizationalGoals": [],
                    "opportunities": [],
                    "process": [],
                    "processCapabilityIds": []
                },
                {
                    "id": 437788,
                    "parentId": 437759,
                    "orderChild": 2,
                    "name": "Human Resources Management",
                    "color": "",
                    "summary": null,
                    "heatmaps": [],
                    "activities": [
                        {
                            "id": 437798,
                            "parentId": 437788,
                            "orderChild": 1,
                            "name": "Personnel",
                            "color": "",
                            "summary": null,
                            "heatmaps": [],
                            "activities": [
                                {
                                    "id": 445458,
                                    "parentId": 437798,
                                    "orderChild": 1,
                                    "name": "New Capability",
                                    "color": "",
                                    "summary": null,
                                    "heatmaps": [],
                                    "activities": [],
                                    "isParent": false,
                                    "inputs": [],
                                    "outputs": [],
                                    "systems": [],
                                    "stakeholders": [],
                                    "customers": [],
                                    "suppliers": [],
                                    "levelNumber": "7.1.1",
                                    "organizationalGoals": [],
                                    "opportunities": [],
                                    "process": [],
                                    "processCapabilityIds": []
                                }
                            ],
                            "isParent": false,
                            "inputs": [],
                            "outputs": [],
                            "systems": [],
                            "stakeholders": [],
                            "customers": [],
                            "suppliers": [],
                            "levelNumber": "7.1",
                            "organizationalGoals": [],
                            "opportunities": [],
                            "process": [],
                            "processCapabilityIds": []
                        },
                        {
                            "id": 437799,
                            "parentId": 437788,
                            "orderChild": 2,
                            "name": "Recruitment",
                            "color": "",
                            "summary": null,
                            "heatmaps": [],
                            "activities": [],
                            "isParent": false,
                            "inputs": [],
                            "outputs": [],
                            "systems": [],
                            "stakeholders": [],
                            "customers": [],
                            "suppliers": [],
                            "levelNumber": "7.2",
                            "organizationalGoals": [],
                            "opportunities": [],
                            "process": [],
                            "processCapabilityIds": []
                        },
                        {
                            "id": 437800,
                            "parentId": 437788,
                            "orderChild": 3,
                            "name": "Training",
                            "color": "",
                            "summary": null,
                            "heatmaps": [],
                            "activities": [],
                            "isParent": false,
                            "inputs": [],
                            "outputs": [],
                            "systems": [],
                            "stakeholders": [],
                            "customers": [],
                            "suppliers": [],
                            "levelNumber": "7.3",
                            "organizationalGoals": [],
                            "opportunities": [],
                            "process": [],
                            "processCapabilityIds": []
                        },
                        {
                            "id": 437801,
                            "parentId": 437788,
                            "orderChild": 4,
                            "name": "Staffing",
                            "color": "",
                            "summary": null,
                            "heatmaps": [],
                            "activities": [],
                            "isParent": false,
                            "inputs": [],
                            "outputs": [],
                            "systems": [],
                            "stakeholders": [],
                            "customers": [],
                            "suppliers": [],
                            "levelNumber": "7.4",
                            "organizationalGoals": [],
                            "opportunities": [],
                            "process": [],
                            "processCapabilityIds": []
                        }
                    ],
                    "isParent": false,
                    "inputs": [],
                    "outputs": [],
                    "systems": [],
                    "stakeholders": [],
                    "customers": [],
                    "suppliers": [],
                    "levelNumber": "7",
                    "organizationalGoals": [],
                    "opportunities": [],
                    "process": [],
                    "processCapabilityIds": []
                },
                {
                    "id": 437789,
                    "parentId": 437759,
                    "orderChild": 3,
                    "name": "Technology Development",
                    "color": "",
                    "summary": null,
                    "heatmaps": [],
                    "activities": [
                        {
                            "id": 437802,
                            "parentId": 437789,
                            "orderChild": 1,
                            "name": "Product Design",
                            "color": "",
                            "summary": null,
                            "heatmaps": [],
                            "activities": [],
                            "isParent": false,
                            "inputs": [],
                            "outputs": [],
                            "systems": [],
                            "stakeholders": [],
                            "customers": [],
                            "suppliers": [],
                            "levelNumber": "8.1",
                            "organizationalGoals": [],
                            "opportunities": [],
                            "process": [],
                            "processCapabilityIds": []
                        },
                        {
                            "id": 437803,
                            "parentId": 437789,
                            "orderChild": 2,
                            "name": "Production",
                            "color": "",
                            "summary": null,
                            "heatmaps": [],
                            "activities": [],
                            "isParent": false,
                            "inputs": [],
                            "outputs": [],
                            "systems": [],
                            "stakeholders": [],
                            "customers": [],
                            "suppliers": [],
                            "levelNumber": "8.2",
                            "organizationalGoals": [],
                            "opportunities": [],
                            "process": [],
                            "processCapabilityIds": []
                        },
                        {
                            "id": 437804,
                            "parentId": 437789,
                            "orderChild": 3,
                            "name": "Market Testing",
                            "color": "",
                            "summary": null,
                            "heatmaps": [],
                            "activities": [],
                            "isParent": false,
                            "inputs": [],
                            "outputs": [],
                            "systems": [],
                            "stakeholders": [],
                            "customers": [],
                            "suppliers": [],
                            "levelNumber": "8.3",
                            "organizationalGoals": [],
                            "opportunities": [],
                            "process": [],
                            "processCapabilityIds": []
                        },
                        {
                            "id": 437805,
                            "parentId": 437789,
                            "orderChild": 4,
                            "name": "R&D",
                            "color": "",
                            "summary": null,
                            "heatmaps": [],
                            "activities": [],
                            "isParent": false,
                            "inputs": [],
                            "outputs": [],
                            "systems": [],
                            "stakeholders": [],
                            "customers": [],
                            "suppliers": [],
                            "levelNumber": "8.4",
                            "organizationalGoals": [],
                            "opportunities": [],
                            "process": [],
                            "processCapabilityIds": []
                        }
                    ],
                    "isParent": false,
                    "inputs": [],
                    "outputs": [],
                    "systems": [],
                    "stakeholders": [],
                    "customers": [],
                    "suppliers": [],
                    "levelNumber": "8",
                    "organizationalGoals": [],
                    "opportunities": [],
                    "process": [],
                    "processCapabilityIds": []
                },
                {
                    "id": 437790,
                    "parentId": 437759,
                    "orderChild": 4,
                    "name": "Procurement",
                    "color": "",
                    "summary": null,
                    "heatmaps": [],
                    "activities": [
                        {
                            "id": 437806,
                            "parentId": 437790,
                            "orderChild": 1,
                            "name": "Supplier Management",
                            "color": "",
                            "summary": null,
                            "heatmaps": [],
                            "activities": [],
                            "isParent": false,
                            "inputs": [],
                            "outputs": [],
                            "systems": [],
                            "stakeholders": [],
                            "customers": [],
                            "suppliers": [],
                            "levelNumber": "9.1",
                            "organizationalGoals": [],
                            "opportunities": [],
                            "process": [],
                            "processCapabilityIds": []
                        },
                        {
                            "id": 437807,
                            "parentId": 437790,
                            "orderChild": 2,
                            "name": "Funding",
                            "color": "",
                            "summary": null,
                            "heatmaps": [],
                            "activities": [],
                            "isParent": false,
                            "inputs": [],
                            "outputs": [],
                            "systems": [],
                            "stakeholders": [],
                            "customers": [],
                            "suppliers": [],
                            "levelNumber": "9.2",
                            "organizationalGoals": [],
                            "opportunities": [],
                            "process": [],
                            "processCapabilityIds": []
                        },
                        {
                            "id": 437808,
                            "parentId": 437790,
                            "orderChild": 3,
                            "name": "Subcontracting",
                            "color": "",
                            "summary": null,
                            "heatmaps": [],
                            "activities": [],
                            "isParent": false,
                            "inputs": [],
                            "outputs": [],
                            "systems": [],
                            "stakeholders": [],
                            "customers": [],
                            "suppliers": [],
                            "levelNumber": "9.3",
                            "organizationalGoals": [],
                            "opportunities": [],
                            "process": [],
                            "processCapabilityIds": []
                        },
                        {
                            "id": 437809,
                            "parentId": 437790,
                            "orderChild": 4,
                            "name": "Specification",
                            "color": "",
                            "summary": null,
                            "heatmaps": [],
                            "activities": [],
                            "isParent": false,
                            "inputs": [],
                            "outputs": [],
                            "systems": [],
                            "stakeholders": [],
                            "customers": [],
                            "suppliers": [],
                            "levelNumber": "9.4",
                            "organizationalGoals": [],
                            "opportunities": [],
                            "process": [],
                            "processCapabilityIds": []
                        }
                    ],
                    "isParent": false,
                    "inputs": [],
                    "outputs": [],
                    "systems": [],
                    "stakeholders": [],
                    "customers": [],
                    "suppliers": [],
                    "levelNumber": "9",
                    "organizationalGoals": [],
                    "opportunities": [],
                    "process": [],
                    "processCapabilityIds": []
                }
            ],
            "isParent": false,
            "inputs": [],
            "outputs": [],
            "systems": [],
            "stakeholders": [],
            "customers": [],
            "suppliers": [],
            "levelNumber": null,
            "organizationalGoals": [],
            "opportunities": [],
            "process": [],
            "processCapabilityIds": []
        }
    ]
}