export const themes = {
	light: {
		"--primary-color": "#ffffff",
		"--secondary-color": "#222222",
		"--primary-font": '"Arial", sans-serif',
		"--secondary-font": '"Courier New", monospace',
		"--primary-font-size": "1em",
		"--secondary-font-size": "0.9em",
		"--modal-width": "50%",
		"--button-padding": "10px 20px",
		"--standard-margin": "20px",
		"--text-color": "#000000",
	},
	dark: {
		"--primary-color": "#333333",
		"--secondary-color": "#888888",
		"--primary-font": '"Verdana", sans-serif',
		"--secondary-font": '"Lucida Console", monospace',
		"--primary-font-size": "1.2em",
		"--secondary-font-size": "1em",
		"--modal-width": "60%",
		"--button-padding": "15px 25px",
		"--standard-margin": "20px",
		"--text-color": "#ffffff",
	},
	primary: {
		"--primary-color": "#007bff",
		"--secondary-color": "#6c757d",
		"--primary-font": '"Georgia", serif',
		"--secondary-font": '"Times New Roman", serif',
		"--primary-font-size": "1em",
		"--secondary-font-size": "0.8em",
		"--modal-width": "50%",
		"--button-padding": "10px 20px",
		"--standard-margin": "20px",
		"--text-color": "#000000",
	},
};
